import Link from "next/link";
import { getDatabase } from "@netlify/database";
import { requireAdmin } from "@/lib/admin-auth";

export const metadata = { title: "Pedidos e Orçamentos", robots: { index: false, follow: false } };
export const dynamic = "force-dynamic";

const statusLabel: Record<string, string> = { novo: "Novo", em_atendimento: "Em atendimento", concluido: "Concluído", cancelado: "Cancelado" };
const statusClass: Record<string, string> = { novo: "text-blue-300 bg-blue-500/10 border-blue-500/20", em_atendimento: "text-amber-300 bg-amber-500/10 border-amber-500/20", concluido: "text-green-300 bg-green-500/10 border-green-500/20", cancelado: "text-red-300 bg-red-500/10 border-red-500/20" };
const paymentLabel: Record<string, string> = { approved: "Aprovado", pending: "Pendente", in_process: "Em análise", rejected: "Rejeitado", cancelled: "Cancelado", refunded: "Reembolsado", charged_back: "Contestado", creating: "Criando", error: "Erro" };
const notificationLabel: Record<string, string> = { pending: "Pendente", sending: "Enviando", sent: "Enviada", delivered: "Entregue", read: "Lida", failed: "Falhou" };

export default async function OrdersPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireAdmin();
  const { error } = await searchParams;
  const db = getDatabase();
  const orders = await db.sql`
    SELECT o.id, o.order_number, o.customer_id, o.customer_name, o.items, o.total, o.status, o.source, o.stock_deducted_at,
           o.seller_id, o.seller_name, o.seller_commission_rate, o.commission_amount, o.created_at,
           o.payment_provider, o.payment_id, o.payment_status, o.payment_status_detail, o.payment_method_id,
           o.payment_type_id, o.payment_amount, o.payment_approved_at, o.payment_updated_at,
           n.status AS whatsapp_notification_status, n.attempts AS whatsapp_notification_attempts,
           n.recipient AS whatsapp_notification_recipient, n.last_error AS whatsapp_notification_error,
           n.sent_at AS whatsapp_notification_sent_at, n.delivered_at AS whatsapp_notification_delivered_at,
           n.read_at AS whatsapp_notification_read_at
    FROM orders o
    LEFT JOIN LATERAL (
      SELECT status, attempts, recipient, last_error, sent_at, delivered_at, read_at
      FROM order_notifications
      WHERE order_id = o.id AND channel = 'whatsapp' AND notification_type = 'payment_approved_seller'
      ORDER BY created_at DESC
      LIMIT 1
    ) n ON TRUE
    ORDER BY o.created_at DESC LIMIT 100
  `;
  const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
  const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" });
  const openCount = orders.filter((order: any) => ["novo", "em_atendimento"].includes(String(order.status))).length;
  const completedCount = orders.filter((order: any) => String(order.status) === "concluido").length;
  const totalQuoted = orders.reduce((sum: number, order: any) => sum + Number(order.total || 0), 0);

  return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-12">
    <div className="flex flex-wrap items-end justify-between gap-5"><div className="min-w-0"><p className="text-sm font-black uppercase tracking-widest text-blue-400">Vitória Informática</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Pedidos e orçamentos</h1><p className="mt-3 text-zinc-400">Acompanhe vendas, pagamentos, vendedores, comissões e notificações automáticas.</p></div><div className="flex flex-wrap items-center gap-2 text-sm"><Link href="/admin/vendedores" className="rounded-lg border border-green-500/30 px-3 py-2 font-bold text-green-300">Vendedores</Link><Link href="/admin/clientes" className="rounded-lg bg-blue-600 px-3 py-2 font-bold hover:bg-blue-500">Clientes</Link><Link href="/admin" className="rounded-lg border border-zinc-700 px-3 py-2 font-bold hover:bg-zinc-800">← Painel</Link></div></div>
    {error ? <div className="mt-6 rounded-2xl border border-red-500/20 bg-red-500/10 p-4 text-sm font-bold text-red-300">{error}</div> : null}
    <div className="mt-10 grid gap-5 sm:grid-cols-3"><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><p className="text-sm text-zinc-400">Aguardando atendimento</p><p className="mt-2 text-4xl font-black text-amber-400">{openCount}</p></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><p className="text-sm text-zinc-400">Concluídos</p><p className="mt-2 text-4xl font-black text-green-400">{completedCount}</p></div><div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6"><p className="text-sm text-zinc-400">Valor registrado</p><p className="mt-2 text-3xl font-black text-blue-400">{money.format(totalQuoted)}</p></div></div>
    <section className="mt-10 space-y-4">{orders.length === 0 ? <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-8 text-zinc-400">Nenhum pedido registrado ainda.</div> : orders.map((order: any) => { const items = Array.isArray(order.items) ? order.items : []; const stockDeducted = Boolean(order.stock_deducted_at); const isMercadoPago = String(order.payment_provider || "") === "mercado_pago"; const paymentStatus = String(order.payment_status || ""); const notificationStatus = String(order.whatsapp_notification_status || ""); const notificationOk = ["sent", "delivered", "read"].includes(notificationStatus); return <article key={String(order.id)} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-black">{String(order.order_number)}</h2><span className={`rounded-full border px-3 py-1 text-xs font-bold ${statusClass[String(order.status)] || "border-zinc-700 text-zinc-300"}`}>{statusLabel[String(order.status)] || String(order.status)}</span>{stockDeducted ? <span className="rounded-full border border-green-500/20 bg-green-500/10 px-3 py-1 text-xs font-bold text-green-300">Estoque baixado</span> : null}{isMercadoPago ? <span className={`rounded-full border px-3 py-1 text-xs font-bold ${paymentStatus === "approved" ? "border-green-500/20 bg-green-500/10 text-green-300" : paymentStatus === "rejected" || paymentStatus === "cancelled" || paymentStatus === "error" ? "border-red-500/20 bg-red-500/10 text-red-300" : "border-blue-500/20 bg-blue-500/10 text-blue-300"}`}>MP: {paymentLabel[paymentStatus] || paymentStatus || "Aguardando"}</span> : null}{notificationStatus ? <span className={`rounded-full border px-3 py-1 text-xs font-bold ${notificationOk ? "border-green-500/20 bg-green-500/10 text-green-300" : notificationStatus === "failed" ? "border-red-500/20 bg-red-500/10 text-red-300" : "border-amber-500/20 bg-amber-500/10 text-amber-300"}`}>WhatsApp: {notificationLabel[notificationStatus] || notificationStatus}</span> : null}</div><p className="mt-2 text-sm text-zinc-400">{order.customer_name ? <>Cliente: {order.customer_id ? <Link href={`/admin/clientes/${encodeURIComponent(String(order.customer_id))}/editar`} className="font-bold text-blue-300 hover:underline">{String(order.customer_name)}</Link> : String(order.customer_name)} • </> : null}{date.format(new Date(String(order.created_at)))}</p>{order.seller_name ? <p className="mt-2 text-sm font-bold text-green-300">Vendedor: {String(order.seller_name)} • Comissão {Number(order.seller_commission_rate || 0).toFixed(2).replace(".",",")}%{order.commission_amount != null ? ` • ${money.format(Number(order.commission_amount))}` : ""}</p> : <p className="mt-2 text-xs text-zinc-500">Venda direta da loja</p>}</div><strong className="text-2xl text-blue-400">{money.format(Number(order.total))}</strong></div>
      {isMercadoPago ? <div className="mt-4 rounded-xl border border-blue-500/20 bg-blue-500/5 p-4 text-sm"><p className="font-black text-blue-300">Mercado Pago</p><div className="mt-2 grid gap-1 text-zinc-400 sm:grid-cols-2"><p>Status: <strong className="text-zinc-200">{paymentLabel[paymentStatus] || paymentStatus || "Aguardando"}</strong></p><p>Método: <strong className="text-zinc-200">{String(order.payment_method_id || order.payment_type_id || "—")}</strong></p><p>ID: <strong className="text-zinc-200">{String(order.payment_id || "—")}</strong></p><p>Valor confirmado: <strong className="text-zinc-200">{order.payment_amount != null ? money.format(Number(order.payment_amount)) : "—"}</strong></p></div>{paymentStatus === "approved" && !stockDeducted ? <p className="mt-3 rounded-lg border border-amber-500/20 bg-amber-500/10 p-3 font-bold text-amber-300">Pagamento aprovado, mas o estoque não foi baixado automaticamente. Revise este pedido antes de entregar ou reembolsar.</p> : null}</div> : null}
      {notificationStatus ? <div className="mt-4 rounded-xl border border-green-500/20 bg-green-500/5 p-4 text-sm"><p className="font-black text-green-300">Notificação automática do vendedor</p><p className="mt-2 text-zinc-400">Status: <strong className="text-zinc-200">{notificationLabel[notificationStatus] || notificationStatus}</strong> • Tentativas: <strong className="text-zinc-200">{Number(order.whatsapp_notification_attempts || 0)}</strong></p>{order.whatsapp_notification_error ? <p className="mt-2 break-words text-red-300">Erro: {String(order.whatsapp_notification_error)}</p> : null}{["pending", "failed"].includes(notificationStatus) ? <form action={`/api/admin/orders/${encodeURIComponent(String(order.id))}/whatsapp`} method="post" className="mt-3"><button className="rounded-lg border border-green-500/30 bg-green-500/10 px-3 py-2 text-xs font-black text-green-300 hover:bg-green-500/20">Tentar enviar WhatsApp novamente</button></form> : null}</div> : paymentStatus === "approved" && stockDeducted ? <div className="mt-4 rounded-xl border border-zinc-700 bg-zinc-950 p-4 text-sm text-zinc-400">A notificação automática ainda não foi preparada para este pedido.</div> : null}
      <div className="mt-5 space-y-2 rounded-xl bg-zinc-950 p-4">{items.map((item: any, index: number) => <div key={`${String(item.productId)}-${index}`} className="flex justify-between gap-4 text-sm"><span>{Number(item.quantity)}x {String(item.name)}</span><span className="font-bold">{money.format(Number(item.subtotal))}</span></div>)}</div>
      <form action={`/api/admin/orders/${encodeURIComponent(String(order.id))}`} method="post" className="mt-5 flex flex-wrap items-center gap-2"><select name="status" defaultValue={String(order.status)} className="rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm font-bold"><option value="novo">Novo</option><option value="em_atendimento">Em atendimento</option><option value="concluido">Concluído</option><option value="cancelado">Cancelado</option></select><button className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-black hover:bg-blue-500">{stockDeducted ? "Atualizar status" : "Atualizar / confirmar venda"}</button>{!stockDeducted ? <span className="text-xs text-zinc-500">Ao concluir manualmente, baixa estoque e calcula a comissão uma única vez.</span> : <span className="text-xs text-green-400">Venda concluída. Cancelar restaura o estoque, mas não executa reembolso automático no Mercado Pago.</span>}</form>
    </article>; })}</section>
  </main>;
}
